# .gitlab-ci.yml

## Run on the Shell executor specifically
##
default:
  tags: [shell]

stages:
  - base
  - build
  - test

base:
  stage: base
  needs: []
  script:
    - docker build --tag dancelor_base --target base .

deps:
  stage: base
  needs: [base]
  script:
    - docker build --tag dancelor_deps --target deps .

build:
  stage: build
  needs: [deps]
  script:
    - docker build --tag dancelor_build --target build .

build-doc:
  stage: build
  needs: [build]
  script:
    - docker run --cidfile build-doc.cid dancelor_build opam exec -- make doc
    - docker cp --follow-link $(cat build-doc.cid):/wd/doc documentation
  artifacts:
    paths:
      - documentation

files:
  stage: base
  needs: [base]
  script:
    - docker build --tag dancelor_files --target files .

test:
  stage: test
  needs: [build]
  script:
    - docker run dancelor_build opam exec -- make test

## FIXME: enable this test once the repository is ready.
test-indent:
  stage: test
  needs: [files]
  script:
    - docker run dancelor_files ci/indent.sh || true

test-opam-lint:
  stage: test
  needs: [files]
  script:
    - docker run dancelor_files ci/opam-lint.sh

test-opam-diff:
  stage: test
  needs: [files]
  script:
    - docker run dancelor_files ci/opam-diff.sh
