# .gitlab-ci.yml

## Run on the Shell executor specifically
##
default:
  tags: [shell]

## Only run the workflow for pushes to branches. This matters at least for the
## test in `pages` to make sense.
##
workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH'

stages:
  - base
  - build
  - test
  - deploy

base:
  stage: base
  needs: []
  script:
    - docker build --tag dancelor_base --target base .

deps:
  stage: base
  needs: [base]
  script:
    - docker build --tag dancelor_deps --target deps .

build:
  stage: build
  needs: [deps]
  script:
    - docker build --tag dancelor_build --target build .

build-doc:
  stage: build
  needs: [build]
  script:
    - docker run --cidfile build-doc.cid dancelor_build opam exec -- make doc
    - docker cp --follow-link $(cat build-doc.cid):/wd/doc documentation
  artifacts:
    paths:
      - documentation

files:
  stage: base
  needs: [base]
  script:
    - docker build --tag dancelor_files --target files .

test:
  stage: test
  needs: [build]
  script:
    - docker run dancelor_build opam exec -- make test

test-indent:
  stage: test
  needs: [files]
  script:
    - docker run dancelor_files ci/indent.sh

test-opam-lint:
  stage: test
  needs: [files]
  script:
    - docker run dancelor_files ci/opam-lint.sh

test-opam-diff:
  stage: test
  needs: [files]
  script:
    - docker run dancelor_files ci/opam-diff.sh

pages:
  stage: deploy
  needs: [build-doc]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - mv documentation public
  artifacts:
    paths:
      - public
