open Nes
open Dancelor_common
open Model_new
open Utils

let display_warnings warnings =
  let open Html in
  let display_times n =
    if n = 1 then []
    else [txt " ("; txt (Int.to_english_string_times n); txt ")"]
  in
  let rec display_sets = function
    | [] -> []
    | (None, n) :: tl ->
      ([txt "standalone"] @ display_times n) :: display_sets tl
    | (Some set, n) :: tl ->
      ([txt "in “"; Formatters_new.Set.name set; txt "”"] @ display_times n) :: display_sets tl
  in
  let rec format_set_list = function
    (* If the warning Duplicate_tune has been logged, the list of sets,
       and hence of html nodes generated by [display_sets] above is never empty *)
    | [] -> assert false
    | [hd] -> hd @ [txt "."]
    | hd :: tl -> hd @ [txt ", "] @ format_set_list tl
  in
  let display_warning warning =
    match warning with
    | Book_view.Empty ->
      li [txt "This book is empty"]
    | Book_view.Duplicate_set set ->
      R.li @@
      S.from_lwt [] @@
      lwt [txt "Set “"; Formatters_new.Set.name set; txt "” appears several times in this book."]
    | Book_view.Duplicate_tune (tune, sets_opt) ->
      R.li @@
      S.from_lwt [] @@
      lwt (txt "Tune “" :: Formatters_new.Tune.name tune :: txt "” appears several times: " :: (display_sets sets_opt |> format_set_list))
    | Book_view.Set_dance_kind_mismatch (set, dance) ->
      R.li @@
      S.from_lwt [] @@
      lwt [txt "Set “"; Formatters_new.Set.name set; txt "” does not have the same kind as its associated dance “"; Formatters_new.Dance.name dance; txt "”."]
  in
  List.map display_warning warnings

let table_contents ~this_id content =
  let open Html in
  Utils.Tables.make
    ~header: [""; ""; ""; ""; ""]
    (
      tbody
        (
          List.mapi
            (fun pageno page ->
              let preview_href = Endpoints.Page.(href @@ Book Preview) this_id pageno in
              let suffix = [
                td ~a: [a_class ["p-0"; "text-end"]] [
                  Button.make_a
                    ~classes: ["btn-sm"; "btn-outline-secondary"]
                    ~href: (S.const preview_href)
                    ~icon: (Action Preview)
                    ~tooltip: "Preview the book at this page."
                    ()
                ]
              ]
              in
              match page with
              | Book_view.Part title ->
                Any_result_new.make_part_result
                  ~prefix: [td [txt "Part"]]
                  ~suffix
                  title
              | Book_view.Dance (dance, Dance_only) ->
                Any_result_new.make_dance_result
                  ~prefix: [td [txt "Dance"]]
                  ~suffix
                  dance
              | Book_view.Dance (dance, Dance_versions versions_and_params) ->
                Any_result_new.make_dance_plus_versions_result
                  ~prefix: [td [txt "Dance"; Any_result.details [txt (if List.is_singleton versions_and_params then "+Tune" else "+Tunes")]]]
                  ~suffix
                  dance
                  versions_and_params
              | Book_view.Dance (dance, Dance_set (set, params)) ->
                Any_result_new.make_dance_plus_set_result
                  ~prefix: [td [txt "Dance"; Any_result.details [txt "+Set"]]]
                  ~suffix
                  dance
                  set
                  ~set_params: params
              | Book_view.Versions versions_and_params ->
                Any_result_new.make_versions_result
                  ~prefix: [td [txt @@ if List.is_singleton versions_and_params then "Tune" else "Tunes"]]
                  ~suffix
                  versions_and_params
              | Book_view.Set (set, params) ->
                Any_result_new.make_set_or_forbidden_result
                  ~prefix: [td [txt "Set"]]
                  ~suffix
                  ~params
                  set
            )
            content
        )
    )

open Html

let view in_search id =
  Main_page.madge_call_or_404 (Book Get_view) id @@ fun book ->
  Page.make'
    ~parent_title: "Book"
    ~before_title: [Components.Context_links.for_search in_search (Any_id.Book id)]
    ~title: (lwt book.name)
    ~subtitles: [span (Formatters_new.Book.date_and_editors book)]
    ~share_new: (Book id)
    ~actions: [
      lwt [
        Button.make
          ~label: "Download PDF/ZIP"
          ~icon: (Other File_pdf)
          ~onclick: (fun _ -> ignore <$> Book_download_dialog.create_and_open book)
          ~dropdown: true
          ();
      ];
      (
        (* FIXME: check permission to know whether to show this *)
        (* match%lwt Permission.can_update_private book with *)
        (* | None -> lwt_nil *)
        (* | Some _ -> *)
        lwt [
          Button.make_a
            ~label: "Edit"
            ~icon: (Action Edit)
            ~href: (S.const @@ Endpoints.Page.(href @@ Book Edit) id)
            ~dropdown: true
            ();
        ]
      );
      (
        (* FIXME: check permission to know whether to show this *)
        (* match%lwt Permission.can_delete_private book with *)
        (* | None -> lwt_nil *)
        (* | Some _ -> *)
        lwt [
          Action.delete
            ~model: "book"
            ~onclick: (fun () -> Madge_client.call Endpoints.Api.(route @@ Book Delete) id)
            ();
        ]
      );
      (lwt @@ Option.map_to_list (Action.scddb Publication) book.scddb_id);
    ]
    [
      div (
        match book.warnings with
        | [] -> []
        | warnings -> [div ~a: [a_class ["alert"; "alert-warning"]] [ul ~a: [a_class ["mb-0"]] (display_warnings warnings)]]
      );
      div [
        h3 [txt "Contents"];
        table_contents ~this_id: id book.content;
      ];
    ]

let parent_title_and_title = function
  | Book_view.Part name -> ("Part", name)
  | Dance (dance, Dance_only) -> ("Dance", dance.name)
  | Dance (dance, Dance_versions [_]) -> ("Dance+Version", dance.name)
  | Dance (dance, Dance_versions _) -> ("Dance+Versions", dance.name)
  | Dance (dance, Dance_set _) -> ("Dance+Set", dance.name)
  | Versions [] -> assert false
  | Versions [(version, _)] -> ("Version", version.tune.name)
  | Versions ((first_version, _) :: _) -> ("Versions", spf "%s etc." first_version.tune.name)
  | Set (Allowed set, _) -> ("Set", set.name)
  | Set (Forbidden, _) -> ("Set", "<forbidden>")

let subtitles = function
  | Book_view.Part _ -> lwt_nil
  | Dance (dance, dance_page) ->
    let%lwt dance = Madge_client.call_exn Endpoints.Api.(route @@ Dance Get_view) dance.Dance_row.id in
    let%lwt more_subtitles =
      match dance_page with
      | Dance_only -> lwt_nil
      | Dance_versions [(version, _)] ->
        let%lwt version = Madge_client.call_exn Endpoints.Api.(route @@ Version Get_view) version.Version_row.id in
        lwt @@ Version_viewer.subtitles version.tune
      | Dance_versions _ -> lwt_nil
      | Dance_set (Allowed set, _params) ->
        let%lwt set = Madge_client.call_exn Endpoints.Api.(route @@ Set Get_view) set.Set_row.id in
        lwt @@ Set_viewer.subtitles set
      | Dance_set (Forbidden, _) -> lwt_nil
    in
    lwt @@ Dance_viewer.subtitles dance @ more_subtitles
  | Versions [] -> assert false
  | Versions [(version, _)] ->
    let%lwt version = Madge_client.call_exn Endpoints.Api.(route @@ Version Get_view) version.Version_row.id in
    lwt @@ Version_viewer.subtitles version.tune
  | Versions versions_and_params ->
    let versions = List.map fst versions_and_params in
    let%lwt versions = Lwt_list.map_s (fun version -> Madge_client.call_exn Endpoints.Api.(route @@ Version Get_view) version.Version_row.id) versions in
    lwt @@ List.concat_map (fun version -> Version_viewer.subtitles version.Version_view.tune) versions
  | Set (Allowed set, _) ->
    let%lwt set = Madge_client.call_exn Endpoints.Api.(route @@ Set Get_view) set.Set_row.id in
    lwt @@ Set_viewer.subtitles set
  | Set (Forbidden, _) ->
    lwt_nil

let body_dance (dance : Dance_row.t) =
  let%lwt dance = Madge_client.call_exn Endpoints.Api.(route @@ Dance Get_view) dance.id in
  lwt @@ Dance_viewer.body dance

let body_versions = function
  | [(version, _params)] ->
    let%lwt version = Madge_client.call_exn Endpoints.Api.(route @@ Version Get_view) version.Version_row.id in
    lwt @@ Version_viewer.body (`Version version.id) version.tune (Some version)
  | versions ->
    lwt @@ Set_viewer.body_gen versions None

let body_set (set : Set_row.t) =
  let%lwt set = Madge_client.call_exn Endpoints.Api.(route @@ Set Get_view) set.id in
  lwt @@ Set_viewer.body set

let body = function
  | Book_view.Part _ -> lwt [txt "This is a part; nothing to see here."]
  | Dance (dance, Dance_only) -> body_dance dance
  | Dance (_dance, Dance_versions versions) -> body_versions versions
  | Dance (_dance, Dance_set (Allowed set, _params)) -> body_set set
  | Dance (_dance, Dance_set (Forbidden, _params)) -> lwt [txt "You do not have access to this set; nothing to see here."]
  | Versions versions -> body_versions versions
  | Set (Allowed set, _) -> body_set set
  | Set (Forbidden, _params) -> lwt [txt "You do not have access to this set; nothing to see here."]

let preview id pageno =
  Main_page.madge_call_or_404 (Book Get_view) id @@ fun book ->
  let page = List.nth book.content pageno in
  let (parent_title, title) = parent_title_and_title page in
  let%lwt subtitles = subtitles page in
  let%lwt body = body page in
  Page.make'
    ~parent_title
    ~before_title: [Components.Context_links.for_book book pageno]
    ~title: (lwt title)
    ~subtitles
    body
