;; This file was generated by ./gen_dune_sqlgg

;; book.sql
(rule
 (target book_sql.ml)
 (deps schema.sql ctes.sql book.sql)
 (action
  (with-stdout-to %{target}
   (run sqlgg -gen caml_io -dialect postgresql %{deps}))))

;; ctes.sql
;; supporting file: no Dune rule

;; dance.sql
(rule
 (target dance_sql.ml)
 (deps schema.sql ctes.sql dance.sql)
 (action
  (with-stdout-to %{target}
   (run sqlgg -gen caml_io -dialect postgresql %{deps}))))

;; entry.sql
(rule
 (target entry_sql.ml)
 (deps schema.sql ctes.sql entry.sql)
 (action
  (with-stdout-to %{target}
   (run sqlgg -gen caml_io -dialect postgresql %{deps}))))

;; migrations.sql
(rule
 (target migrations_sql.ml)
 (deps migrations.sql)
 (action
  (with-stdout-to %{target}
   (run sqlgg -gen caml_io -dialect postgresql %{deps}))))

;; person.sql
(rule
 (target person_sql.ml)
 (deps schema.sql ctes.sql person.sql)
 (action
  (with-stdout-to %{target}
   (run sqlgg -gen caml_io -dialect postgresql %{deps}))))

;; schema.sql
;; supporting file: no Dune rule

;; set.sql
(rule
 (target set_sql.ml)
 (deps schema.sql ctes.sql set.sql)
 (action
  (with-stdout-to %{target}
   (run sqlgg -gen caml_io -dialect postgresql %{deps}))))

;; source.sql
(rule
 (target source_sql.ml)
 (deps schema.sql ctes.sql source.sql)
 (action
  (with-stdout-to %{target}
   (run sqlgg -gen caml_io -dialect postgresql %{deps}))))

;; tune.sql
(rule
 (target tune_sql.ml)
 (deps schema.sql ctes.sql tune.sql)
 (action
  (with-stdout-to %{target}
   (run sqlgg -gen caml_io -dialect postgresql %{deps}))))

;; user.sql
(rule
 (target user_sql.ml)
 (deps schema.sql ctes.sql user.sql)
 (action
  (with-stdout-to %{target}
   (run sqlgg -gen caml_io -dialect postgresql %{deps}))))

;; version.sql
(rule
 (target version_sql.ml)
 (deps schema.sql ctes.sql version.sql)
 (action
  (with-stdout-to %{target}
   (run sqlgg -gen caml_io -dialect postgresql %{deps}))))

