#!/usr/bin/env bash
set -eufo pipefail

mariadb-dump \
    --no-data \
    --ignore-table=dancelor.migrations \
    --skip-dump-date \
    --skip-add-drop-table \
    --skip-add-locks \
    --skip-comments \
    --skip-disable-keys \
    --skip-set-charset \
    dancelor \
    \
    | sed 's/\/\*.*\*\/;*//g' \
    | sed 's/) ENGINE=[^;]*;/);/' \
    | cat -s \
    | sed -e '/./,$!d' -e :a -e '/^\n*$/{$d;N;ba' -e '}'
