#!/usr/bin/env bash
set -eufo pipefail

SQLFLUFF=sqlfluff
if [ "${1:-}" = "--sqlfluff" ]; then
    SQLFLUFF=$2
    shift 2
fi

## RF06 flags unnecessarily-quoted identifiers; we prefer quoting all identifiers.
## LT05 flags lines longer than 80 characters.
"$SQLFLUFF" \
    fix \
    --ignore-local-config \
    --dialect mysql \
    --exclude-rules RF06,LT05 \
    --show-lint-violations \
    "$@"
