name: Deployment

on:
  push:
    branches: [main]
    tags: ["*"]

jobs:
  dispatch:
    name: Dispatch to niols/nixos-config
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch update event to niols/nixos-config
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.NIXOS_CONFIG_WORKFLOW_DISPATCH_TOKEN }}
          repository: niols/nixos-config
          event-type: bump-dancelor
