name: OPAM

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

## We specify a concurrency group with automated cancellation. This means that
## other pushes on the same `github.ref` (eg. other pushes to the same pull
## request) cancel previous occurrences of the CI.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.14.x

      - name: Install OPAM dependencies
        run: opam install . --deps-only --with-doc --with-test

      - name: Build Dancelor
        run: opam exec -- make

      - name: Build documentation
        run: opam exec -- make doc

      - name: Run tests
        run: opam exec -- make test
