module Person = Generic.Make (Dancelor_common_model.Person)
module Credit = Generic.Make (Dancelor_common_model.Credit)
module Source = Generic.Make (Dancelor_common_model.Source)
module Dance = Generic.Make (Dancelor_common_model.Dance)
module Tune = Generic.Make (Dancelor_common_model.Tune)
module TuneGroup = Generic.Make (Dancelor_common_model.TuneGroup)
module Set = Generic.Make (Dancelor_common_model.Set)
module Program = Generic.Make (Dancelor_common_model.Program)
